env = Environment(CPPPATH = ['kernel/include', 'cpu/linux/include', 'libc/include'])
src = Glob('libc/*.c')
src = src + Glob('cpu/*.S')
src = src + Glob('kernel/*.c')
src = src + Glob('cpu/linux/*.c')
src = src + Glob('app/*.c')
src = src + Glob('middleware/shell_parser/*.c')
env.Program('fos',src, CFLAGS = ['-g', '-fcolor-diagnostics', '-Werror'], CC = 'clang')
