import config
env = Environment(tools = ['mingw'],
	AS = config.AS, ASFLAGS = config.AFLAGS,
	CC = config.CC, CCFLAGS = config.CFLAGS,
	AR = config.AR, ARFLAGS = '-rc',
	LINK = config.LINK, LINKFLAGS = config.LFLAGS)
env.PrependENVPath('PATH', config.EXEC_PATH)

obj = env.Object(Glob("*.c")) 
obj = env.Object(Glob("*.S"))  
Return("obj")  
